### ISSUE TITLE
Clarify metadata signing status

### ISSUE THREAD

**Issue by kommendorkapten** [jku/repository-playground#139]
The output during signing today is:

```
root is verified and signed by 2/2 (4/2) signers (user1, user2, user3, user4)
```

It's not obvious what 2/2 and (4/2) refers too, this could be clarified, like:

```
root is verified and signed by 2/2 current signers and 4/2 new (user1, user2, user3, user4)
```

Happy for more in input in making this clear. Not sure if current and new are the best names though.

**Comment by jku** [comment]
moved to tuf-on-ci
