### ISSUE TITLE
git-repo: Find and fix issue with public key adding

### ISSUE THREAD

**Issue by jku** [jku/repository-playground#46]
* In a test run of `playground-delegate root` 
* a new signer was added as root signer
* configured user-name was the signer that was added

for some reason the tool did not ask to insert the HW key (to add the public key to role). This should have happened in `delegate.py:_update_offline_role()`

**Comment by jku** [comment]
FYI @kommendorkapten: the not-adding-public-key looks like a simple typo -- but this is a great example why a test suite is something that should be pretty high on TODO list...

**Comment by kommendorkapten** [comment]
Agree 100%
