### ISSUE TITLE
Some user stories could be more TUF-agnostic

### ISSUE THREAD

**Issue by lukpueh** [jku/repository-playground#8]
Maybe this does not make a big difference, but I think the user stories would be stronger if they weren't motivated by a TUF setup. E.g. all the "downloader user" stories work well regardless of TUF being used or not.

The following user stories, otoh, feel like jumping ahead a bit: 

- “Modify top level metadata” (repo admin)
- “Modify top level keys” (repo admin)
- “Modify keys/threshold for a project” (project admin)

I suggest to first list the *genuine* desires/tasks related to each user category (e.g. repo admin wants to authorize project maintainer to sign artifacts for a project), and only in a later step describe how this is realized in a TUF setup (e.g. add keys in top-level metadata).

**Comment by jku** [comment]
very good points, totally agreed
