### ISSUE TITLE
rename "target" to "artifact"

### ISSUE THREAD

**Issue by jku** [jku/repository-playground#92]
The issue is that TUF (spec and implementation) overloads the word target:
* "targets" is a metadata type
* "target file" is an artifact 

This is especially an issue in UI and code where target files are being handled. I think consistently calling them artifacts would alleviate the problem. This is also in-line with what rstuf (another repository implementation) does.

**Comment by lukpueh** [comment]
I support this. And the same suggestion has been made on the TUF spec issue tracker:  https://github.com/theupdateframework/specification/issues/149#issuecomment-878436226

"artifact" is definitely the right word for this thing these days.

**Comment by jku** [comment]
moved to tuf-on-ci
